/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package testRCBApi;

//import org.junit.jupiter.api.Test;

import testRCBApi.Library;

import static org.junit.jupiter.api.Assertions.*;

import org.testng.annotations.Test;

class LibraryTest {
    @Test void someLibraryMethodReturnsTrue() {
        Library classUnderTest = new Library();
        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'");
    }
}
